---
title: "Untitled"
author: "Marco Lax"
date: "16/12/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load Data and packages

```{r}
source("../r_klimanotstand/load_packages.R")
```
# Transport data

```{r}
fahrplaene_2019 <- read.csv("../data/Busverkehr/2019_FAHRPLAENE.csv", sep=";")
fahrplaene_2020 <- read.csv("../data/Busverkehr/2020_FAHRPLAENE.csv", sep=";")

fahrten_2019 <- read.csv("../data/Busverkehr/2019_FAHRTEN.csv", sep=";")
fahrten_2020 <- read.csv("../data/Busverkehr/2020_FAHRTEN.csv", sep=";")

fahrhaltezeiten_2019 <- read.csv("../data/Busverkehr/2019_FAHRTHALTEZEITEN.csv", sep=";")
fahrhaltezeiten_2020 <- read.csv("data/Busverkehr/2020_FAHRTHALTEZEITEN.csv", sep=";")

fahrwege_2019 <- read.csv("../data/Busverkehr/2019_FAHRWEGE.csv", sep=";")
fahrwege_2020 <- read.csv("../data/Busverkehr/2020_FAHRWEGE.csv", sep=";")

fahrzeiten_2019 <- read.csv("../data/Busverkehr/2019_FAHRZEITEN.csv", sep=";")
fahrzeiten_2020 <- read.csv("../data/Busverkehr/2020_FAHRZEITEN.csv", sep=";")

firmenkalender_2019 <- read.csv("../data/Busverkehr/2019_FIRMENKALENDER.csv", sep=";")
firmenkalender_2020 <- read.csv("../data/Busverkehr/2020_FIRMENKALENDER.csv", sep=";")

linien_2019 <- read.csv("../data/Busverkehr/2019_FIRMENKALENDER.csv", sep=";")
linien_2020 <- read.csv("../data/Busverkehr/2020_FIRMENKALENDER.csv", sep=";")

orte_2019 <- read.csv("../data/Busverkehr/2019_ORTE.csv", sep=";")
orte_2020 <- read.csv("../data/Busverkehr/2019_ORTE.csv", sep=";")

verbindungen_2019 <- read.csv("../data/Busverkehr/2019_VERBINDUNGEN.csv", sep=";")
verbindungen_2020 <- read.csv("../data/Busverkehr/2020_VERBINDUNGEN.csv", sep=";")

```

# Explore dataset

```{r}
fahrten_ <- fahrten_2019 %>% select()
```

# Heatmap Solarpotential

```{r}
solarpotenzial_2018 <- read.csv("../data/Solarpotenzial_2018.csv")

# load packages
pacman::p_load(leaflet, leaflet.extras, leaflet.extras2, mapview, tidyverse, webshot, rgdal,
               data.table,htmltools, htmlwidgets, readr, tidyr, install = T, update = F)

```

```{r}
solarpotenzial_2018 <- solarpotenzial_2018 %>% select(strasse, hausnummer, zusatz, ort,
                                                      ortsteil, roof_class, solflaeche,
                                                      pvleistung, ertr_leist, pvco2, solanlage,
                                                      Shape__Area, Shape_Leng, Shape__Length)


map_basic <- leaflet() %>% 
  addProviderTiles(provider = "CartoDB.Voyager") %>% 
  enableTileCaching() %>% 
  setView(lat = 47.67304974982142, lng = 9.183714827775331, zoom = 14) 


```









